{% set name = "webdrivermanager" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/webdrivermanager-{{ version }}.tar.gz
  sha256: c313a71340f0bb7bfef8b03763a0b1b323473e1cc3945a86f3230e78529af067

build:
  number: 1
  noarch: python
  entry_points:
    - webdrivermanager = webdrivermanager.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - appdirs
    - beautifulsoup4
    - lxml
    - python >={{ python_min }}
    - requests
    - tqdm

test:
  imports:
    - webdrivermanager
  commands:
    - pip check
    - webdrivermanager --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rasjani/webdrivermanager
  summary: Module for facilitating download and deploy of WebDriver binaries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
